//////////////////////////////////////////////////////////////////////////////////
// ad9361_txq_search
// TX quadrature calibration with RX-NCO phase search, run entirely in PL after the LUT init.
// Mirrors ADI no-OS ad9361_tx_quad_phase_search():
//   ENSM -> ALERT, RX quad tracking off
//   for phase 0..31: 0x0A0 = {RX_NCO_FREQ, phase}; 0x0A1 = cfg|SOFT_RESET; 0x0A1 = cfg; 0x016 = TX_QUAD_CAL;
//                    wait 0x016[4]==0; converged = (0x0A7[1:0] == 2'b11)
//   phase = centre of the longest (circular) run of converged phases (DEFAULT_PHASE if none)
//   final TX quad cal at that phase, restore 0x169 / 0x014, wait ENSM == FDD
// SPI access uses the same request/ack interface as ad9361_config (O_start strobe, I_waitrequest low = done).
//////////////////////////////////////////////////////////////////////////////////
module ad9361_txq_search #(
    parameter [1:0]  RX_NCO_FREQ   = 2'd2,          // 0x0A0[6:5] as generated by the Eval-Software script
    parameter [1:0]  M_DECIM       = 2'd3,          // 0x0A1[1:0]
    parameter [4:0]  DEFAULT_PHASE = 5'd4,          // used when no phase converges
    parameter [15:0] POLL_MAX      = 16'hFFFF       // max polls of a status register (~1.4 us each)
)(
    input                               I_clk                      ,        //20mhz, same clock as ad9361_spi
    input                               I_rst_n                    ,
    input                               I_start                    ,        //1-cycle strobe: run the search

    output reg                          O_start                    ,        //SPI request strobe
    output reg                          O_read                     ,
    output reg                          O_write                    ,
    output reg         [   9: 0]        O_address                  ,
    output reg         [   7: 0]        O_writedata                ,
    input              [   7: 0]        I_readdata                 ,
    input                               I_waitrequest              ,

    output reg                          O_busy                     ,        //owns the SPI bus while high
    output reg                          O_done                     ,        //at least one search finished
    output reg                          O_err                      ,        //ENSM/cal timeout in the last search
    output reg         [   4: 0]        O_phase                    ,        //chosen RX NCO phase offset
    output reg         [  31: 0]        O_field                    ,        //bit p = converged at phase p
    output reg         [   5: 0]        O_run_len                  ,        //length of the chosen run
    output reg         [   1: 0]        O_status                            //0x0A7[1:0] after the final cal
);

    localparam [5:0]
        S_IDLE      = 6'd0,
        S_XFER      = 6'd1,     // issue one SPI transfer, then return to ret_state
        S_XWAIT     = 6'd2,
        S_A_RD014   = 6'd3,
        S_A_WR014   = 6'd4,
        S_A_RD017   = 6'd5,
        S_A_CHK017  = 6'd6,
        S_A_RD169   = 6'd7,
        S_A_WR169   = 6'd8,
        S_C_WR0A0   = 6'd9,
        S_C_WR0A1R  = 6'd10,
        S_C_WR0A1   = 6'd11,
        S_C_WR016   = 6'd12,
        S_C_RD016   = 6'd13,
        S_C_CHK016  = 6'd14,
        S_C_RD0A7   = 6'd15,
        S_C_CHK0A7  = 6'd16,
        S_R_INIT    = 6'd17,
        S_R_LEN     = 6'd18,
        S_R_NEXT    = 6'd19,
        S_R_PICK    = 6'd20,
        S_F_WR169   = 6'd21,
        S_F_WR014   = 6'd22,
        S_F_RD017   = 6'd23,
        S_F_CHK017  = 6'd24,
        S_DONE      = 6'd25;

    reg                [   5: 0]        state                       ;
    reg                [   5: 0]        ret_state                   ;
    reg                [   7: 0]        rdata                       ;
    reg                [  15: 0]        poll_cnt                    ;
    reg                [   7: 0]        save_014                    ;
    reg                [   7: 0]        save_169                    ;
    reg                [   4: 0]        cur_phase                   ;
    reg                                 final_run                   ;
    reg                [   4: 0]        run_s                       ;       //run search: start index
    reg                [   5: 0]        run_len                     ;       //run search: current length
    reg                [   5: 0]        best_len                    ;
    reg                [   4: 0]        best_start                  ;
    wire               [   4: 0]        run_idx = run_s + run_len[4:0];     //wraps mod 32

    // queue one SPI transfer and continue at `ret` when it has finished
    task xfer(input rd, input [9:0] addr, input [7:0] wdata, input [5:0] ret);
        begin
            O_read      <= rd;
            O_write     <= ~rd;
            O_address   <= addr;
            O_writedata <= wdata;
            ret_state   <= ret;
            state       <= S_XFER;
        end
    endtask

    always @ (posedge I_clk or negedge I_rst_n) begin
        if (!I_rst_n) begin
            state       <= S_IDLE;
            ret_state   <= S_IDLE;
            O_start     <= 1'b0;
            O_read      <= 1'b0;
            O_write     <= 1'b0;
            O_address   <= 10'd0;
            O_writedata <= 8'd0;
            O_busy      <= 1'b0;
            O_done      <= 1'b0;
            O_err       <= 1'b0;
            O_phase     <= DEFAULT_PHASE;
            O_field     <= 32'd0;
            O_run_len   <= 6'd0;
            O_status    <= 2'd0;
            rdata       <= 8'd0;
            poll_cnt    <= 16'd0;
            save_014    <= 8'd0;
            save_169    <= 8'd0;
            cur_phase   <= 5'd0;
            final_run   <= 1'b0;
            run_s       <= 5'd0;
            run_len     <= 6'd0;
            best_len    <= 6'd0;
            best_start  <= 5'd0;
        end
        else begin
            O_start <= 1'b0;
            case (state)
            S_IDLE: begin
                if (I_start) begin
                    O_busy    <= 1'b1;
                    O_err     <= 1'b0;
                    O_field   <= 32'd0;
                    final_run <= 1'b0;
                    cur_phase <= 5'd0;
                    poll_cnt  <= 16'd0;
                    state     <= S_A_RD014;
                end
            end

            // ---- generic SPI transfer ----
            S_XFER: begin
                O_start <= 1'b1;
                state   <= S_XWAIT;
            end
            S_XWAIT: begin
                if (!O_start && !I_waitrequest) begin
                    rdata <= I_readdata;
                    state <= ret_state;
                end
            end

            // ---- enter ALERT, stop RX quad tracking ----
            S_A_RD014:  xfer(1'b1, 10'h014, 8'h00, S_A_WR014);
            S_A_WR014: begin
                save_014 <= rdata;
                xfer(1'b0, 10'h014, 8'h0D, S_A_RD017);        // LEVEL_MODE | FORCE_ALERT_STATE | TO_ALERT
            end
            S_A_RD017:  xfer(1'b1, 10'h017, 8'h00, S_A_CHK017);
            S_A_CHK017: begin
                if (rdata[3:0] == 4'h5) begin
                    poll_cnt <= 16'd0;
                    state    <= S_A_RD169;
                end
                else if (poll_cnt == POLL_MAX) begin
                    O_err <= 1'b1;
                    state <= S_F_WR014;                       // nothing touched yet except 0x014
                end
                else begin
                    poll_cnt <= poll_cnt + 1'b1;
                    state    <= S_A_RD017;
                end
            end
            S_A_RD169:  xfer(1'b1, 10'h169, 8'h00, S_A_WR169);
            S_A_WR169: begin
                save_169 <= rdata;
                xfer(1'b0, 10'h169, rdata & 8'hFC, S_C_WR0A0); // clear ENABLE_TRACKING_MODE_CH1/CH2
            end

            // ---- one TX quad cal at cur_phase ----
            S_C_WR0A0:  xfer(1'b0, 10'h0A0, {1'b0, RX_NCO_FREQ, cur_phase}, S_C_WR0A1R);
            S_C_WR0A1R: xfer(1'b0, 10'h0A1, {6'b011111, M_DECIM}, S_C_WR0A1);  // SETTLE|DC|GAIN|PHASE|SOFT_RESET
            S_C_WR0A1:  xfer(1'b0, 10'h0A1, {6'b011110, M_DECIM}, S_C_WR016);  // SETTLE|DC|GAIN|PHASE
            S_C_WR016: begin
                poll_cnt <= 16'd0;
                xfer(1'b0, 10'h016, 8'h10, S_C_RD016);        // start TX_QUAD_CAL
            end
            S_C_RD016:  xfer(1'b1, 10'h016, 8'h00, S_C_CHK016);
            S_C_CHK016: begin
                if (!rdata[4])
                    state <= S_C_RD0A7;
                else if (poll_cnt == POLL_MAX) begin
                    O_err <= 1'b1;
                    state <= S_F_WR169;
                end
                else begin
                    poll_cnt <= poll_cnt + 1'b1;
                    state    <= S_C_RD016;
                end
            end
            S_C_RD0A7:  xfer(1'b1, 10'h0A7, 8'h00, S_C_CHK0A7);
            S_C_CHK0A7: begin
                if (final_run) begin
                    O_status <= rdata[1:0];
                    state    <= S_F_WR169;
                end
                else begin
                    O_field[cur_phase] <= &rdata[1:0];
                    if (cur_phase == 5'd31)
                        state <= S_R_INIT;
                    else begin
                        cur_phase <= cur_phase + 1'b1;
                        state     <= S_C_WR0A0;
                    end
                end
            end

            // ---- longest circular run of converged phases ----
            S_R_INIT: begin
                run_s      <= 5'd0;
                run_len    <= 6'd0;
                best_len   <= 6'd0;
                best_start <= 5'd0;
                state      <= S_R_LEN;
            end
            S_R_LEN: begin
                if (run_len != 6'd32 && O_field[run_idx])
                    run_len <= run_len + 1'b1;
                else
                    state <= S_R_NEXT;
            end
            S_R_NEXT: begin
                if (run_len > best_len) begin
                    best_len   <= run_len;
                    best_start <= run_s;
                end
                run_len <= 6'd0;
                if (run_s == 5'd31)
                    state <= S_R_PICK;
                else begin
                    run_s <= run_s + 1'b1;
                    state <= S_R_LEN;
                end
            end
            S_R_PICK: begin
                cur_phase <= (best_len == 6'd0) ? DEFAULT_PHASE : (best_start + best_len[5:1]);
                O_phase   <= (best_len == 6'd0) ? DEFAULT_PHASE : (best_start + best_len[5:1]);
                O_run_len <= best_len;
                final_run <= 1'b1;
                state     <= S_C_WR0A0;
            end

            // ---- restore tracking and ENSM ----
            S_F_WR169:  xfer(1'b0, 10'h169, save_169, S_F_WR014);
            S_F_WR014: begin
                poll_cnt <= 16'd0;
                xfer(1'b0, 10'h014, save_014, S_F_RD017);
            end
            S_F_RD017:  xfer(1'b1, 10'h017, 8'h00, S_F_CHK017);
            S_F_CHK017: begin
                if (rdata[3:0] == 4'hA)
                    state <= S_DONE;
                else if (poll_cnt == POLL_MAX) begin
                    O_err <= 1'b1;
                    state <= S_DONE;
                end
                else begin
                    poll_cnt <= poll_cnt + 1'b1;
                    state    <= S_F_RD017;
                end
            end
            S_DONE: begin
                O_busy <= 1'b0;
                O_done <= 1'b1;
                state  <= S_IDLE;
            end
            default: state <= S_IDLE;
            endcase
        end
    end

endmodule
